(cl:defpackage dcsc_fpga-srv
  (:use )
  (:export
   "CONTR"
   "<CONTR-REQUEST>"
   "CONTR-REQUEST"
   "<CONTR-RESPONSE>"
   "CONTR-RESPONSE"
   "MOPSREAD"
   "<MOPSREAD-REQUEST>"
   "MOPSREAD-REQUEST"
   "<MOPSREAD-RESPONSE>"
   "MOPSREAD-RESPONSE"
   "MOPSWRITE"
   "<MOPSWRITE-REQUEST>"
   "MOPSWRITE-REQUEST"
   "<MOPSWRITE-RESPONSE>"
   "MOPSWRITE-RESPONSE"
  ))

