// Generated by gencpp from file dcsc_fpga/ContrRequest.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_CONTRREQUEST_H
#define DCSC_FPGA_MESSAGE_CONTRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dcsc_fpga
{
template <class ContainerAllocator>
struct ContrRequest_
{
  typedef ContrRequest_<ContainerAllocator> Type;

  ContrRequest_()
    : angle(0.0)
    , velocity(0.0)  {
    }
  ContrRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::dcsc_fpga::ContrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcsc_fpga::ContrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ContrRequest_

typedef ::dcsc_fpga::ContrRequest_<std::allocator<void> > ContrRequest;

typedef boost::shared_ptr< ::dcsc_fpga::ContrRequest > ContrRequestPtr;
typedef boost::shared_ptr< ::dcsc_fpga::ContrRequest const> ContrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcsc_fpga::ContrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcsc_fpga::ContrRequest_<ContainerAllocator1> & lhs, const ::dcsc_fpga::ContrRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcsc_fpga::ContrRequest_<ContainerAllocator1> & lhs, const ::dcsc_fpga::ContrRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcsc_fpga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::ContrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::ContrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::ContrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "add030c9a3ec13fc469e071a948d4d33";
  }

  static const char* value(const ::dcsc_fpga::ContrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadd030c9a3ec13fcULL;
  static const uint64_t static_value2 = 0x469e071a948d4d33ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcsc_fpga/ContrRequest";
  }

  static const char* value(const ::dcsc_fpga::ContrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n"
"float64 velocity\n"
;
  }

  static const char* value(const ::dcsc_fpga::ContrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcsc_fpga::ContrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcsc_fpga::ContrRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_CONTRREQUEST_H
