// Generated by gencpp from file dcsc_fpga/ContrResponse.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_CONTRRESPONSE_H
#define DCSC_FPGA_MESSAGE_CONTRRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dcsc_fpga
{
template <class ContainerAllocator>
struct ContrResponse_
{
  typedef ContrResponse_<ContainerAllocator> Type;

  ContrResponse_()
    : action(0.0)  {
    }
  ContrResponse_(const ContainerAllocator& _alloc)
    : action(0.0)  {
  (void)_alloc;
    }



   typedef double _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::dcsc_fpga::ContrResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcsc_fpga::ContrResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ContrResponse_

typedef ::dcsc_fpga::ContrResponse_<std::allocator<void> > ContrResponse;

typedef boost::shared_ptr< ::dcsc_fpga::ContrResponse > ContrResponsePtr;
typedef boost::shared_ptr< ::dcsc_fpga::ContrResponse const> ContrResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcsc_fpga::ContrResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcsc_fpga::ContrResponse_<ContainerAllocator1> & lhs, const ::dcsc_fpga::ContrResponse_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcsc_fpga::ContrResponse_<ContainerAllocator1> & lhs, const ::dcsc_fpga::ContrResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcsc_fpga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::ContrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::ContrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::ContrResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "478a7595ad560d2b162ccf6437c172d9";
  }

  static const char* value(const ::dcsc_fpga::ContrResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x478a7595ad560d2bULL;
  static const uint64_t static_value2 = 0x162ccf6437c172d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcsc_fpga/ContrResponse";
  }

  static const char* value(const ::dcsc_fpga::ContrResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 action\n"
"\n"
;
  }

  static const char* value(const ::dcsc_fpga::ContrResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContrResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcsc_fpga::ContrResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcsc_fpga::ContrResponse_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<double>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_CONTRRESPONSE_H
