// Generated by gencpp from file dcsc_fpga/MopsReadRequest.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_MOPSREADREQUEST_H
#define DCSC_FPGA_MESSAGE_MOPSREADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dcsc_fpga
{
template <class ContainerAllocator>
struct MopsReadRequest_
{
  typedef MopsReadRequest_<ContainerAllocator> Type;

  MopsReadRequest_()
    {
    }
  MopsReadRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MopsReadRequest_

typedef ::dcsc_fpga::MopsReadRequest_<std::allocator<void> > MopsReadRequest;

typedef boost::shared_ptr< ::dcsc_fpga::MopsReadRequest > MopsReadRequestPtr;
typedef boost::shared_ptr< ::dcsc_fpga::MopsReadRequest const> MopsReadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace dcsc_fpga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dcsc_fpga::MopsReadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcsc_fpga/MopsReadRequest";
  }

  static const char* value(const ::dcsc_fpga::MopsReadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::dcsc_fpga::MopsReadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MopsReadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcsc_fpga::MopsReadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::dcsc_fpga::MopsReadRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_MOPSREADREQUEST_H
