// Generated by gencpp from file dcsc_fpga/MopsRead.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_MOPSREAD_H
#define DCSC_FPGA_MESSAGE_MOPSREAD_H

#include <ros/service_traits.h>


#include <dcsc_fpga/MopsReadRequest.h>
#include <dcsc_fpga/MopsReadResponse.h>


namespace dcsc_fpga
{

struct MopsRead
{

typedef MopsReadRequest Request;
typedef MopsReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MopsRead
} // namespace dcsc_fpga


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dcsc_fpga::MopsRead > {
  static const char* value()
  {
    return "d795c28c5471b5cffac720eee35784ef";
  }

  static const char* value(const ::dcsc_fpga::MopsRead&) { return value(); }
};

template<>
struct DataType< ::dcsc_fpga::MopsRead > {
  static const char* value()
  {
    return "dcsc_fpga/MopsRead";
  }

  static const char* value(const ::dcsc_fpga::MopsRead&) { return value(); }
};


// service_traits::MD5Sum< ::dcsc_fpga::MopsReadRequest> should match
// service_traits::MD5Sum< ::dcsc_fpga::MopsRead >
template<>
struct MD5Sum< ::dcsc_fpga::MopsReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dcsc_fpga::MopsRead >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dcsc_fpga::MopsReadRequest> should match
// service_traits::DataType< ::dcsc_fpga::MopsRead >
template<>
struct DataType< ::dcsc_fpga::MopsReadRequest>
{
  static const char* value()
  {
    return DataType< ::dcsc_fpga::MopsRead >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dcsc_fpga::MopsReadResponse> should match
// service_traits::MD5Sum< ::dcsc_fpga::MopsRead >
template<>
struct MD5Sum< ::dcsc_fpga::MopsReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dcsc_fpga::MopsRead >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dcsc_fpga::MopsReadResponse> should match
// service_traits::DataType< ::dcsc_fpga::MopsRead >
template<>
struct DataType< ::dcsc_fpga::MopsReadResponse>
{
  static const char* value()
  {
    return DataType< ::dcsc_fpga::MopsRead >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_MOPSREAD_H
