// Generated by gencpp from file dcsc_fpga/MopsWrite.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_MOPSWRITE_H
#define DCSC_FPGA_MESSAGE_MOPSWRITE_H

#include <ros/service_traits.h>


#include <dcsc_fpga/MopsWriteRequest.h>
#include <dcsc_fpga/MopsWriteResponse.h>


namespace dcsc_fpga
{

struct MopsWrite
{

typedef MopsWriteRequest Request;
typedef MopsWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MopsWrite
} // namespace dcsc_fpga


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dcsc_fpga::MopsWrite > {
  static const char* value()
  {
    return "e4d7c08e31b1435de7c05d537862ef59";
  }

  static const char* value(const ::dcsc_fpga::MopsWrite&) { return value(); }
};

template<>
struct DataType< ::dcsc_fpga::MopsWrite > {
  static const char* value()
  {
    return "dcsc_fpga/MopsWrite";
  }

  static const char* value(const ::dcsc_fpga::MopsWrite&) { return value(); }
};


// service_traits::MD5Sum< ::dcsc_fpga::MopsWriteRequest> should match
// service_traits::MD5Sum< ::dcsc_fpga::MopsWrite >
template<>
struct MD5Sum< ::dcsc_fpga::MopsWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dcsc_fpga::MopsWrite >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dcsc_fpga::MopsWriteRequest> should match
// service_traits::DataType< ::dcsc_fpga::MopsWrite >
template<>
struct DataType< ::dcsc_fpga::MopsWriteRequest>
{
  static const char* value()
  {
    return DataType< ::dcsc_fpga::MopsWrite >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dcsc_fpga::MopsWriteResponse> should match
// service_traits::MD5Sum< ::dcsc_fpga::MopsWrite >
template<>
struct MD5Sum< ::dcsc_fpga::MopsWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dcsc_fpga::MopsWrite >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dcsc_fpga::MopsWriteResponse> should match
// service_traits::DataType< ::dcsc_fpga::MopsWrite >
template<>
struct DataType< ::dcsc_fpga::MopsWriteResponse>
{
  static const char* value()
  {
    return DataType< ::dcsc_fpga::MopsWrite >::value();
  }
  static const char* value(const ::dcsc_fpga::MopsWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_MOPSWRITE_H
