// Generated by gencpp from file dcsc_fpga/MopsReadResponse.msg
// DO NOT EDIT!


#ifndef DCSC_FPGA_MESSAGE_MOPSREADRESPONSE_H
#define DCSC_FPGA_MESSAGE_MOPSREADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dcsc_fpga/MopsSensors.h>

namespace dcsc_fpga
{
template <class ContainerAllocator>
struct MopsReadResponse_
{
  typedef MopsReadResponse_<ContainerAllocator> Type;

  MopsReadResponse_()
    : success(false)
    , message()
    , sensors()  {
    }
  MopsReadResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , sensors(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::dcsc_fpga::MopsSensors_<ContainerAllocator>  _sensors_type;
  _sensors_type sensors;





  typedef boost::shared_ptr< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MopsReadResponse_

typedef ::dcsc_fpga::MopsReadResponse_<std::allocator<void> > MopsReadResponse;

typedef boost::shared_ptr< ::dcsc_fpga::MopsReadResponse > MopsReadResponsePtr;
typedef boost::shared_ptr< ::dcsc_fpga::MopsReadResponse const> MopsReadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator1> & lhs, const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.sensors == rhs.sensors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator1> & lhs, const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dcsc_fpga

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d795c28c5471b5cffac720eee35784ef";
  }

  static const char* value(const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd795c28c5471b5cfULL;
  static const uint64_t static_value2 = 0xfac720eee35784efULL;
};

template<class ContainerAllocator>
struct DataType< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcsc_fpga/MopsReadResponse";
  }

  static const char* value(const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"dcsc_fpga/MopsSensors sensors\n"
"\n"
"\n"
"================================================================================\n"
"MSG: dcsc_fpga/MopsSensors\n"
"Header header\n"
"float64 position0\n"
"float64 position1\n"
"float64 speed\n"
"float64 voltage\n"
"float64 current\n"
"float64 external_voltage\n"
"uint8 digital_inputs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.sensors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MopsReadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dcsc_fpga::MopsReadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dcsc_fpga::MopsReadResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "sensors: ";
    s << std::endl;
    Printer< ::dcsc_fpga::MopsSensors_<ContainerAllocator> >::stream(s, indent + "  ", v.sensors);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DCSC_FPGA_MESSAGE_MOPSREADRESPONSE_H
